In [34]:
import pandas as pd

# Load datasets
fake_df = pd.read_csv("../data/Fake.csv")
true_df = pd.read_csv("../data/True.csv")

# Show first 5 rows
print("Fake News Dataset")
display(fake_df.head())

print("Real News Dataset")
display(true_df.head())

Fake News Dataset

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

Real News Dataset

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [35]:
# Check dataset shape

print("Fake Dataset Shape:", fake_df.shape)
print("True Dataset Shape:", true_df.shape)

Fake Dataset Shape: (23481, 4)
True Dataset Shape: (21417, 4)

In [36]:
# Check column names

print(fake_df.columns)
print(true_df.columns)

Index(['title', 'text', 'subject', 'date'], dtype='str')
Index(['title', 'text', 'subject', 'date'], dtype='str')

In [37]:
# Check missing values

print("Fake News Missing Values")
print(fake_df.isnull().sum())

print("\nReal News Missing Values")
print(true_df.isnull().sum())

Fake News Missing Values
title      0
text       0
subject    0
date       0
dtype: int64

Real News Missing Values
title      0
text       0
subject    0
date       0
dtype: int64

In [38]:
# Add labels

fake_df["label"] = 0   # Fake news
true_df["label"] = 1   # Real news

# Verify
print(fake_df.head())
print(true_df.head())

                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...
1   Drunk Bragging Trump Staffer Started Russian ...
2   Sheriff David Clarke Becomes An Internet Joke...
3   Trump Is So Obsessed He Even Has Obama’s Name...
4   Pope Francis Just Called Out Donald Trump Dur...

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News
1  House Intelligence Committee Chairman Devin Nu...    News
2  On Friday, it was revealed that former Milwauk...    News
3  On Christmas day, Donald Trump announced that ...    News
4  Pope Francis used his annual Christmas Day mes...    News

                date  label
0  December 31, 2017      0
1  December 31, 2017      0
2  December 30, 2017      0
3  December 29, 2017      0
4  December 25, 2017      0
                                               title  \
0  As U.S. budget fight looms, Republicans flip t...
1  U.S. military to accept transgender recruits o...
2  Senior U.S. Republican senator: 'Let Mr. Muell...
3  FBI Russia probe helped by Australian diplomat...
4  Trump wants Postal Service to charge 'much mor...

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews

                 date  label
0  December 31, 2017       1
1  December 29, 2017       1
2  December 31, 2017       1
3  December 30, 2017       1
4  December 29, 2017       1

In [39]:
# Combine datasets

news_df = pd.concat([fake_df, true_df], axis=0)

# Shuffle dataset
news_df = news_df.sample(frac=1, random_state=42)

# Reset index
news_df.reset_index(drop=True, inplace=True)

print(news_df.shape)
news_df.head()

(44898, 5)

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [40]:
# Check label distribution

print(news_df["label"].value_counts())

label
0    23481
1    21417
Name: count, dtype: int64

In [41]:
# Combine title and text

news_df["content"] = news_df["title"] + " " + news_df["text"]

# Keep only useful columns
news_df = news_df[["content", "label"]]

# Show dataset
news_df.head()

                                             content  label
0  Ben Stein Calls Out 9th Circuit Court: Committ...      0
1  Trump drops Steve Bannon from National Securit...      1
2  Puerto Rico expects U.S. to lift Jones Act shi...      1
3   OOPS: Trump Just Accidentally Confirmed He Le...      0
4  Donald Trump heads for Scotland to reopen a go...      1

In [42]:
# Check shape again

print(news_df.shape)

(44898, 2)

In [43]:
# Check for duplicates

print("Duplicate rows:", news_df.duplicated().sum())

Duplicate rows: 5793

In [44]:
# Remove duplicates

news_df.drop_duplicates(inplace=True)

# Reset index
news_df.reset_index(drop=True, inplace=True)

print("New Shape:", news_df.shape)

New Shape: (39105, 2)

In [45]:
# Verify duplicates removed

print("Duplicate rows:", news_df.duplicated().sum())

Duplicate rows: 0

In [46]:
import re
import string

In [47]:
# Text cleaning function

def clean_text(text):
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    
    # Remove extra spaces
    text = text.strip()
    
    return text

In [48]:
# Apply text cleaning

news_df["content"] = news_df["content"].apply(clean_text)

# Show cleaned data
news_df.head()

                                             content  label
0  ben stein calls out th circuit court committed...      0
1  trump drops steve bannon from national securit...      1
2  puerto rico expects us to lift jones act shipp...      1
3  oops trump just accidentally confirmed he leak...      0
4  donald trump heads for scotland to reopen a go...      1

In [49]:
import nltk
print("Working perfectly")

Working perfectly

In [50]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

print("NLTK working perfectly")

NLTK working perfectly

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [51]:
# Create stop words set
stop_words = set(stopwords.words('english'))

# Function for tokenization + stopword removal
def remove_stopwords(text):
    words = word_tokenize(text)

    filtered_words = [
        word for word in words
        if word not in stop_words and word.isalpha()
    ]

    return " ".join(filtered_words)

# Apply preprocessing
news_df["content"] = news_df["content"].apply(remove_stopwords)

# Check output
news_df.head()

                                             content  label
0  ben stein calls th circuit court committed cou...      0
1  trump drops steve bannon national security cou...      1
2  puerto rico expects us lift jones act shipping...      1
3  oops trump accidentally confirmed leaked israe...      0
4  donald trump heads scotland reopen golf resort...      1

In [52]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [53]:
import sklearn
print(sklearn.__version__)

from sklearn.model_selection import train_test_split
print("sklearn working")

1.8.0
sklearn working

In [54]:
# Features and labels
X = news_df["content"]
y = news_df["label"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Check shapes
print(X_train.shape)
print(X_test.shape)

(31284,)
(7821,)

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Convert text into numbers
vectorizer = TfidfVectorizer(max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

print(X_train_vec.shape)
print(X_test_vec.shape)

(31284, 5000)
(7821, 5000)

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Train improved model
model = LogisticRegression(max_iter=1000)

model.fit(X_train_vec, y_train)

# Predictions
y_pred = model.predict(X_test_vec)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9859353023909986

In [57]:
from sklearn.metrics import classification_report, confusion_matrix

# Confusion Matrix
print(confusion_matrix(y_test, y_pred))

# Classification Report
print(classification_report(y_test, y_pred))

[[3459   77]
 [  33 4252]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      3536
           1       0.98      0.99      0.99      4285

    accuracy                           0.99      7821
   macro avg       0.99      0.99      0.99      7821
weighted avg       0.99      0.99      0.99      7821

In [58]:
import joblib

# Save improved model
joblib.dump(model, "../models/fake_news_model.pkl")

# Save vectorizer
joblib.dump(vectorizer, "../models/tfidf_vectorizer.pkl")

print("Improved model saved successfully!")

Improved model saved successfully!

In [59]:
import joblib

# Load model and vectorizer
model = joblib.load("../models/fake_news_model.pkl")
vectorizer = joblib.load("../models/tfidf_vectorizer.pkl")


def predict_news(news_text):
    # Convert text into vector
    text_vector = vectorizer.transform([news_text])

    # Prediction
    prediction = model.predict(text_vector)

    if prediction[0] == 0:
        return "Fake News"
    else:
        return "Real News"


# Test
sample_news = input("Enter news text: ")

result = predict_news(sample_news)

print("Prediction:", result)

Prediction: Fake News